### ISSUE TITLE
ScrollView doesn't scroll on iOS

### ISSUE THREAD

**Issue by faceoffers28** [cemahseri/MauiFinance#1] opened 2022-10-17 20:46 UTC
ScrollView doesn't scroll on iOS until I move to landscape and then back to portrait. I'm running Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.3.6 with Xamarin.iOS version 16.0.0.75. My target is net6.0-ios14.5. Minimum target is 13.0,

Is there an easy fix for this?

**Comment by cemahseri** [comment] 2022-10-26 10:27
I cannot reproduce it since I do not have a Mac for compiling and testing the iOS version. Honestly, I don't have any idea about this bug. Closing this and the #2, but feel free to open if you have something new. Sorry about this.

**Closed as completed by cemahseri** 2022-10-26 10:27 UTC
